/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package admin;
import java.awt.event.ActionEvent;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matthew
 */
public class Add_Tutor extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	SqlQuery_admin query = null;
	private boolean b; 
	/**
     * Creates new form Add_Tutor_Nb
     */
    public Add_Tutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	doesExistTB = new javax.swing.JToggleButton();
        topPanel = new JPanel();
        titleLbl = new JLabel();
        doesExistLbl = new JLabel();
        doesExistPanel = new JPanel();
        UINLbl = new JLabel();
        fNameLbl = new JLabel();
        lNameLbl = new JLabel();
        uNameLbl = new JLabel();
        passLbl = new JLabel();
        valPassLbl = new JLabel();
        emailLbl = new JLabel();
        valEmailLbl = new JLabel();
        passTF = new java.awt.TextField();
        valPassTF = new java.awt.TextField();
        emailTF = new java.awt.TextField();
        valemailTF = new java.awt.TextField();
        uinTF = new java.awt.TextField();
        fnameTF = new java.awt.TextField();
        lnameTF = new java.awt.TextField();
        unameTF = new java.awt.TextField();
        jPanel3 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        // Test model
        model.setColumnIdentifiers(new String[]{"Roll No", "Name", "Class", "Section"});
        model.addRow(new String[]{"1", "Happy", "Warrior", "Inner"});
        model.addRow(new String[]{"2", "Sad", "Mage", "Outter"});
        model.addRow(new String[]{"3", "Jug Head", "Clown", "Outter space"});
        // end model
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Add Tutor");
           	
        doesExistTB.setText("Does Exist"); 
      
        doesExistLbl.setText("Student Already exists.  Click to add student as a Tutor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(doesExistTB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doesExistLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doesExistTB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doesExistLbl))
                .addContainerGap())
        );

        doesExistTB.getAccessibleContext().setAccessibleName("Does Exists");
        doesExistTB.getAccessibleContext().setAccessibleDescription("");

        UINLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UINLbl.setText("UIN:                  ");

        fNameLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fNameLbl.setText("First Name:       ");

        lNameLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lNameLbl.setText("Last Name:     ");

        uNameLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uNameLbl.setText("Username:     ");

        passLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passLbl.setText("Password:      ");

        valPassLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valPassLbl.setText("Confirm Password:  ");

        emailLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailLbl.setText("E-mail:           ");

        valEmailLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valEmailLbl.setText("Confirm E-mail:           ");

        passTF.setText("passTF");

        valPassTF.setText("passTF");

        emailTF.setText("emailTF");

        valemailTF.setText("emailTF");

        uinTF.setText("uinTF");

        fnameTF.setText("fnameTF");

        lnameTF.setText("lnameTF");

        unameTF.setText("unameTF");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(doesExistPanel);
        doesExistPanel.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valPassLbl)
                    .addComponent(passLbl)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(valEmailLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(emailLbl))
                    .addComponent(UINLbl)
                    .addComponent(fNameLbl)
                    .addComponent(lNameLbl)
                    .addComponent(uNameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valemailTF, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(valPassTF, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(passTF)
                    .addComponent(emailTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unameTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lnameTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uinTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fnameTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uinTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UINLbl))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fNameLbl)
                    .addComponent(fnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lNameLbl)
                        .addGap(19, 19, 19))
                    .addComponent(lnameTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uNameLbl)
                    .addComponent(unameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLbl)
                    .addComponent(valPassTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valPassLbl)
                    .addComponent(passTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(valemailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(emailLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valEmailLbl)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        uinTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uinTFactionPerformed(evt);
            }

        });
        
        addBtn.setText("Submit");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Cancel");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(doesExistPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doesExistPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void uinTFactionPerformed(ActionEvent evt) {
		uin = uinTF.getText(); 
		query.doesStudentExist(b, uin);
		if(b = true){
			System.out.println("Tutor exists");	
			emailTF.setText("email");
			uinTF.setText(uin);
			fnameTF.setText("fname");
			lnameTF.setText("lname"); 
			unameTF.setText("uname");
		
			
		}
	}
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	Object source = evt.getSource();

		if (source == addBtn) {
            
				
	        
			}else{
				System.out.println("Tutor does not exist"); 
				
				query.insertStudent(); 
				dispose();   
			query.insertStudent();
			
			}
			System.out.println("Student tutor Added");
		}

		/*if (source == clB) {
			new CardLogin();
			dispose();
		}
		if (source == cB) {
			System.exit(0);
		}
		if (source == rB) {
			new CardSwipeRequest();	
			dispose();
		}*/


    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    	query.setUIN(uinTF.getText()); 
	    query.removeStudent();
	    
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn,removeBtn;
    private javax.swing.JLabel titleLbl,valEmailLbl,doesExistLbl,UINLbl,fNameLbl,lNameLbl,uNameLbl,passLbl,valPassLbl;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JPanel topPanel,doesExistPanel,jPanel3;
    private javax.swing.JToggleButton doesExistTB;
    private java.awt.TextField emailTF,valemailTF,uinTF,fnameTF,lnameTF,unameTF, passTF, valPassTF;
    String uin, uname, pass, valPass, email, valemail, fname, lname; 
    DefaultTableModel model = new DefaultTableModel();
    // End of variables declaration//GEN-END:variables
}
