package admin;

//import admin.report.PrinttoJasper;
import java.awt.event.ActionEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JToggleButton;

import report.PrinttoJasper;
import src.PrintLog;
import src.Testing;
import src.Tutor;

/**
 *
 * @author matthew
 */
public class Administration extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String startDate, endDate, tutorName, selection;
    private ArrayList<Object> tutorArr;
    private ArrayList<Object> testArr;
	private String selectUIN;

    /**
     * Creates new form Administration
     */
    public Administration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        midPanel = new javax.swing.JPanel();
        tutorPanel = new javax.swing.JPanel();
        cbTutor = new javax.swing.JComboBox<Object>();
        btnTutor_Add = new javax.swing.JButton();
        btnTutor_remove = new javax.swing.JButton();
        waiverPanel = new javax.swing.JPanel();
        cbWaiver = new javax.swing.JComboBox<Object>();
        btnWaiver_Add = new javax.swing.JButton();
        btnWaiver_Remove = new javax.swing.JButton();
        btnTutor = new javax.swing.JToggleButton();
        btnWaiver = new javax.swing.JToggleButton();
        buttonPanel = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        reportPanel = new javax.swing.JPanel();
        startDatelbl = new javax.swing.JLabel();
        endDatelbl = new javax.swing.JLabel();
        btnPrint_Ok = new javax.swing.JButton();
        btnPrint_Cancel = new javax.swing.JButton();
        jXDatePicker_start = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker_end = new org.jdesktop.swingx.JXDatePicker();
        printTxt_lbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCarina = new javax.swing.JToggleButton();
        btnStudent = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        btnPrint_Report = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1522, 814));
        setMinimumSize(new java.awt.Dimension(1522, 814));
        setName("AdminFrame"); // NOI18N
        setResizable(false);

        titleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/LSS_Welcome.png"))); // NOI18N

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 730, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                    .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 190, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        tutorPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tutorPanel.setMaximumSize(new java.awt.Dimension(547, 228));
        tutorPanel.setMinimumSize(new java.awt.Dimension(547, 228));
        tutorPanel.setVisible(false);

        cbTutor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tutor tutors = new Tutor(); //creating the instance of the class
        tutorArr = new ArrayList<>();
        tutorArr = tutors.getRecord();
        System.out.println("Line 109 - Adminstration " + " " + tutorArr);
        cbTutor = new JComboBox<Object>(tutorArr.toArray());
        cbTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	actionCBPerformed(evt);
            }


        });

        btnTutor_Add.setText("Add");
        btnTutor_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	actionBtnPerformed(evt);
            }

			
        });

        btnTutor_remove.setText("Remove");
        btnTutor_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	actionBtnPerformed(evt);
            }
        });

        javax.swing.GroupLayout tutorPanelLayout = new javax.swing.GroupLayout(tutorPanel);
        tutorPanel.setLayout(tutorPanelLayout);
        tutorPanelLayout.setHorizontalGroup(
            tutorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorPanelLayout.createSequentialGroup()
                .addGroup(tutorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tutorPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnTutor_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(btnTutor_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tutorPanelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(cbTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        tutorPanelLayout.setVerticalGroup(
            tutorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(cbTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(tutorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTutor_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTutor_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        waiverPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        waiverPanel.setVisible(false);
        waiverPanel.setMaximumSize(new java.awt.Dimension(463, 302));
        waiverPanel.setMinimumSize(new java.awt.Dimension(463, 302));

        //create JComboBox and assign it to the comboBox
        // Get Waiver array
        Testing test = new Testing(); //creating the instance of the class
        testArr = new ArrayList<>();
        testArr = test.getWaiverArr();
        cbWaiver = new JComboBox<Object>(testArr.toArray());
        cbWaiver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnWaiver_Add.setText("Add");
        btnWaiver_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	actionBtnPerformed(evt);
            }
        });

        btnWaiver_Remove.setText("Remove");
        btnWaiver_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	actionBtnPerformed(evt);
            }
        });

        javax.swing.GroupLayout waiverPanelLayout = new javax.swing.GroupLayout(waiverPanel);
        waiverPanel.setLayout(waiverPanelLayout);
        waiverPanelLayout.setHorizontalGroup(
            waiverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waiverPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnWaiver_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnWaiver_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, waiverPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbWaiver, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        waiverPanelLayout.setVerticalGroup(
            waiverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waiverPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(cbWaiver, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(waiverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnWaiver_Add, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btnWaiver_Remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69))
        );

        btnTutor.setText("Add/Remove Tutor");
        btnTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionBtnPerformed(evt);
            }
        });

        btnWaiver.setText("Add/Remove Waiver");
        btnWaiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionBtnPerformed(evt);
            }
        });

        javax.swing.GroupLayout midPanelLayout = new javax.swing.GroupLayout(midPanel);
        midPanel.setLayout(midPanelLayout);
        midPanelLayout.setHorizontalGroup(
            midPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tutorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(waiverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(midPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnWaiver, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        midPanelLayout.setVerticalGroup(
            midPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(midPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWaiver, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(midPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(midPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(tutorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, midPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(waiverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        reportPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reportPanel.setMaximumSize(new java.awt.Dimension(412, 307));
        reportPanel.setMinimumSize(new java.awt.Dimension(412, 307));
        reportPanel.setVisible(false);

        startDatelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        startDatelbl.setText("Start Date");
        startDatelbl.setFocusable(false);

        endDatelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        endDatelbl.setText("End Date");
        endDatelbl.setFocusable(false);

        btnPrint_Ok.setText("Ok");
        btnPrint_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	actionBtnPerformed(evt);
            }
        });

        btnPrint_Cancel.setText("Cancel");
        btnPrint_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	actionBtnPerformed(evt);
            }
        });

        jXDatePicker_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePickerActionPerformed(evt);
            }
        });

        jXDatePicker_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePickerActionPerformed(evt);
            }
        });

        btnCarina.setText("Carina Report");
        btnCarina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	actionBtnPerformed(evt);
            }
        });

        btnStudent.setText("Student Report");
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	actionBtnPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnCarina, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarina, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportPanelLayout.createSequentialGroup()
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(reportPanelLayout.createSequentialGroup()
                                .addComponent(btnPrint_Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPrint_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(reportPanelLayout.createSequentialGroup()
                                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(startDatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(endDatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jXDatePicker_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jXDatePicker_end, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportPanelLayout.createSequentialGroup()
                        .addComponent(printTxt_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePicker_start, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePicker_end, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printTxt_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint_Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrint_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnPrint_Report.setText("Print Report");
        btnPrint_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionBtnPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(btnPrint_Report, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrint_Report, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(midPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7)
                        .addComponent(reportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(midPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)))
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionBtnPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformed
        Object source = evt.getSource();

        if (source == btnPrint_Report) {
        	// print source
            if (btnPrint_Report.isSelected()) {
                reportPanel.setVisible(true);
              } 
            }
            if (source == btnPrint_Ok){
            	System.out.println("startDate to endDate"+ " " + startDate + " " + endDate);
              
                    if (btnCarina.isSelected()) {
            	     selection = "Carina report button pressed";
            	     System.out.println("Line 545: " + selection + " button pressed " + selectUIN);
            	     jasper.selectCarinaRpt(startDate, endDate);
            	}
 
                	if (btnStudent.isSelected()) {
               	     selection = "Student button pressed";
               	     System.out.println("Line 550: " + selection + " button pressed " + selectUIN);
               	     jasper.selectStudentRpt(startDate, endDate);
               	}

            }
            if (source == btnPrint_Cancel){
            	endDate = ""; 
                
                DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
                jXDatePicker_start.setFormats(dateFormat);
                DateFormat sysDate = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                String startDate = sysDate.format(jXDatePicker_start.getDate()).toString();
                
                System.out.println(" start Date" + startDate); 
            }
       
          
        if (source == btnTutor){
        // tutor source
          if (btnTutor.isSelected()) {
            tutorPanel.setVisible(true);
          }
        }
        	if (source == btnTutor_Add){
        		Add_Tutor add = new Add_Tutor();
        		add.setVisible(true);
        	}
        	if (source == btnTutor_remove) {
        	
        	}
        
        if (source == btnWaiver){
        	// waiver source
        if (btnWaiver.isSelected()) {
            waiverPanel.setVisible(true);
        }
        }
        	if(source == btnWaiver_Add){
        		Add_Course addC = new Add_Course();
                addC.setVisible(true);
        	}
        	if(source == btnWaiver_Remove){
        		
        	}  
        
       
    }
  
    private void jXDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker_startActionPerformed
      SimpleDateFormat formater = new SimpleDateFormat("MM/dd/yyyy");
      Object sourceDp = evt.getSource();
      
      			if(sourceDp == jXDatePicker_start){
                    formater.format(jXDatePicker_start.getDate());
                    startDate = formater.format(jXDatePicker_start.getDate());
                    System.out.println("startDate  " + startDate);
      			}
      			if(sourceDp == jXDatePicker_end){
                    SimpleDateFormat formater2 = new SimpleDateFormat("MM/dd/yyyy");
                    formater.format(jXDatePicker_end.getDate());
                    endDate = formater2.format(jXDatePicker_end.getDate());
                    System.out.println("endDate  " + endDate);
      			}   
                  
              
    }//GEN-LAST:event_jXDatePicker_startActionPerformed

     private void actionCBPerformed(ActionEvent evt) {
    	 Object sourceCb = evt.getSource();
    	 if (sourceCb == cbTutor) {
			tutorName = (String)cbTutor.getSelectedItem();
			selection = tutorName;
			System.out.println("Tutor selection" + selection); 				
							
		    }//GEN-LAST:event_cbTutorActionPerformed
		}
		
	

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        PrintLog toLog = new PrintLog();
                    toLog.PrinttoLog();  

    }//GEN-LAST:event_btnSubmitActionPerformed


    public String getStartDate() {
        return startDate;
    }

    public String getEndDate() {
        return endDate;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private JToggleButton btnCarina;
    private javax.swing.JButton btnPrint_Cancel;
    private javax.swing.JButton btnPrint_Ok;
    private javax.swing.JToggleButton btnPrint_Report;
    private JToggleButton btnStudent;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JToggleButton btnTutor;
    private javax.swing.JButton btnTutor_Add;
    private javax.swing.JButton btnTutor_remove;
    private javax.swing.JToggleButton btnWaiver;
    private javax.swing.JButton btnWaiver_Add;
    private javax.swing.JButton btnWaiver_Remove;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JComboBox<Object> cbTutor;
    private javax.swing.JComboBox<Object> cbWaiver;
    private javax.swing.JLabel endDatelbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker_end;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker_start;
    private javax.swing.JPanel midPanel;
    private javax.swing.JLabel printTxt_lbl;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JLabel startDatelbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel tutorPanel;
    private javax.swing.JPanel waiverPanel;
    PrinttoJasper jasper = new PrinttoJasper(); 
    // End of variables declaration//GEN-END:variables

}
